<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #111827; }
        .container { width: 100%; padding: 24px; border: 6px double #1f2937; }
        .title { text-align: center; font-size: 28px; font-weight: 700; margin-bottom: 4px; }
        .subtitle { text-align: center; font-size: 14px; color: #6b7280; margin-bottom: 24px; }
        .panel { border: 1px solid #e5e7eb; padding: 20px; border-radius: 8px; }
        .row { margin: 8px 0; font-size: 14px; }
        .label { color: #6b7280; width: 140px; display: inline-block; }
        .value { font-weight: 600; }
        .footer { margin-top: 28px; font-size: 12px; color: #6b7280; text-align: center; }
    </style>
    <title>Certificate</title>
    </head>
<body>
    <div class="container">
        <div class="title">Certificate of Achievement</div>
        <div class="subtitle">This certifies that the following details have been verified</div>
        <div class="panel">
            <div class="row"><span class="label">Name:</span> <span class="value">{{ $name }}</span></div>
            <div class="row"><span class="label">Email:</span> <span class="value">{{ $email }}</span></div>
            <div class="row"><span class="label">Phone:</span> <span class="value">{{ $phone }}</span></div>
            <div class="row"><span class="label">Serial No.:</span> <span class="value">{{ $serial_number }}</span></div>
            <div class="row"><span class="label">Issued On:</span> <span class="value">{{ $issued_at }}</span></div>
        </div>
        <div class="footer">Generated by Certificate Management System</div>
    </div>
</body>
</html>


