<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #111827; }
        .container { padding: 36px; border: 4px solid #374151; border-radius: 8px; }
        .title { text-align: center; font-size: 28px; margin-bottom: 8px; }
        .subtitle { text-align: center; font-size: 14px; color: #6b7280; margin-bottom: 24px; }
        .field { margin: 8px 0; }
        .label { color: #6b7280; font-size: 12px; }
        .value { font-size: 14px; font-weight: 600; }
        .footer { margin-top: 24px; font-size: 12px; color: #6b7280; text-align: right; }
    </style>
    <title>Certificate</title>
</head>
<body>
    <div class="container">
        <div class="title">Certificate of Verification</div>
        <div class="subtitle">This certifies that the following applicant's documents have been verified</div>

        <div class="field"><span class="label">Name:</span> <span class="value">{{ $name }}</span></div>
        <div class="field"><span class="label">Email:</span> <span class="value">{{ $email }}</span></div>
        <div class="field"><span class="label">Phone:</span> <span class="value">{{ $phone }}</span></div>
        <div class="field"><span class="label">Serial Number:</span> <span class="value">{{ $serial_number }}</span></div>
        <div class="field"><span class="label">Issued At:</span> <span class="value">{{ $issued_at }}</span></div>

        <div class="footer">Generated by Certificate Management System</div>
    </div>
</body>
</html>


